FROM ubuntu
MAINTAINER Aanand
RUN apt -y install wget which sudo openjdk-8-jdk java-1.8.0-openjdk-devel curl
RUN curl --silent --location http://pkg.jenkins-ci.org/redhat-stable/jenkins.repo | sudo tee /etc/yum.repos.d/jenkins.repo
RUN sudo rpm --import https://jenkins-ci.org/redhat/jenkins-ci.org.key
RUN sudo  -y install jenkins
RUN yum -y install initscripts && yum clean all
RUN wget http://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
RUN rpm -ivh epel-release-latest-7.noarch.rpm
RUN  echo "/sbin/service jenkins start" >> .bashrc
ENTRYPOINT service start jenkins
CMD start jenkins
EXPOSE 8080
